# Wybieramy oficjalny obraz Nginx
FROM nginx:latest

# Kopiujemy nasz plik konfiguracyjny do obrazu Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Otwieramy port 80, który będzie nasłuchiwał na zapytania
EXPOSE 80
